title: 'Site Settings'
data:
  site_name: 'CFS Consulting'
  site_description: 'Working with a consultant is an investment in your organization’s future—improve processes now so you can meet any challenge that comes your way.'
