tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Site Name'
              icon: text
              instructions: 'Site name that will appear in copyright footer and other places.'
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: site_description
            field:
              antlers: false
              type: textarea
              display: 'Site Description'
              icon: textarea
              instructions: 'Fallback for SEO.'
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: logo
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Logo
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
